# import libraries

In [1]:
import numpy as np
import pandas as pd

In [1]:
import tensorflow as tf

In [2]:
from tensorflow.keras import datasets

In [3]:
(x_train , y_train), (x_test , y_test) =datasets.mnist.load_data()

11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 3s 0us/step


In [4]:
x_train

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       ...,

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 

In [5]:
x_train.shape        # img , width , height as o/p for train the data

(60000, 28, 28)

In [6]:
x_test.shape        #  img , width , height as o/p for test the data

(10000, 28, 28)

In [7]:
width , height = 28 ,28
input_shape = (width , height , 1)

In [8]:
input_shape

(28, 28, 1)

In [10]:
x_train = x_train.reshape(x_train.shape[0] , height , width , 1)
x_test = x_test.reshape(x_test.shape[0] , height , width , 1)

In [11]:
x_train.shape #visualiza the data 

(60000, 28, 28, 1)

In [12]:
x_test.shape      #data label shape

(10000, 28, 28, 1)

# itteration validation for trainning and testng data 

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
x_train , x_val , y_train , y_val = train_test_split(x_train , y_train , test_size = 0.1)

In [15]:
len(x_train)

54000

In [16]:
len(x_val)

6000

# Normalization the data

In [17]:
x_train = (x_train-x_train.mean())/x_train.std()
x_val = (x_val-x_val.mean())/x_val.std()
x_test = (x_test-x_test.mean())/x_test.std()

In [18]:
x_train

array([[[[-0.42402052],
         [-0.42402052],
         [-0.42402052],
         ...,
         [-0.42402052],
         [-0.42402052],
         [-0.42402052]],

        [[-0.42402052],
         [-0.42402052],
         [-0.42402052],
         ...,
         [-0.42402052],
         [-0.42402052],
         [-0.42402052]],

        [[-0.42402052],
         [-0.42402052],
         [-0.42402052],
         ...,
         [-0.42402052],
         [-0.42402052],
         [-0.42402052]],

        ...,

        [[-0.42402052],
         [-0.42402052],
         [-0.42402052],
         ...,
         [-0.42402052],
         [-0.42402052],
         [-0.42402052]],

        [[-0.42402052],
         [-0.42402052],
         [-0.42402052],
         ...,
         [-0.42402052],
         [-0.42402052],
         [-0.42402052]],

        [[-0.42402052],
         [-0.42402052],
         [-0.42402052],
         ...,
         [-0.42402052],
         [-0.42402052],
         [-0.42402052]]],


       [[[-0.42402052],


In [19]:
y_train

array([0, 9, 7, ..., 0, 2, 1], dtype=uint8)

# convert into categorical data

In [20]:
from tensorflow import keras

In [21]:
num_label = 10

y_train = keras.utils.to_categorical(y_train)

In [22]:
y_train

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 1., 0., 0.],
       ...,
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.]])

In [23]:
y_val = keras.utils.to_categorical(y_val)
y_test = keras.utils.to_categorical(y_test)

# model

In [25]:
from tensorflow.keras.models import Sequential

In [26]:
from tensorflow.keras.layers import Dense , Dropout , Flatten,Input, Conv2D , MaxPooling2D , AveragePooling2D

In [27]:
model = Sequential()

# 1..feature mapping (using lenet5 architecture)

In [29]:
model.add(Conv2D(6 , kernel_size =(5 ,5), strides = (1 ,1),activation = 'tanh' , input_shape = (28, 28, 1)))
model.add(AveragePooling2D(pool_size = (2 ,2) , strides = (1, 1)))
model.add(Conv2D(16 , kernel_size =(5 ,5), strides = (1 ,1),activation = 'tanh'))
model.add(AveragePooling2D(pool_size = (2 ,2) , strides = (2, 2)))
model.add(Conv2D(120 , kernel_size =(5 ,5), strides = (1 ,1),activation = 'tanh'))

model.add(Flatten())
model.add(Dense(84 , activation = 'tanh'))
model.add(Dense(num_label, activation = 'softmax'))

C:\Users\HP\anaconda3\lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


# 2...compile the model

In [30]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ conv2d (Conv2D)                      │ (None, 24, 24, 6)           │             156 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ average_pooling2d (AveragePooling2D) │ (None, 23, 23, 6)           │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_1 (Conv2D)                    │ (None, 19, 19, 16)          │           2,416 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ average_pooling2d_1                  │ (None, 9, 9, 16)            │               0 │
│ (AveragePooling2D)                   │                             │                 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_2 (Conv2D)                    │ (None, 5, 5, 120)           │          48,120 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ flatten (Flatten)                    │ (None, 3000)                │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ (None, 84)                  │         252,084 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 10)                  │             850 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 303,626 (1.16 MB)

 Trainable params: 303,626 (1.16 MB)

 Non-trainable params: 0 (0.00 B)

# 3....compile our architecture

In [31]:
model.compile(loss = keras.losses.categorical_crossentropy,optimizer = 'adam',metrics =['accuracy'])

# 4...train our model

In [33]:
history = model.fit(x_train , y_train ,batch_size = 32 , epochs = 20 ,verbose =1 ,validation_data =(x_val , y_val))

Epoch 1/20
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 29s 15ms/step - accuracy: 0.9022 - loss: 0.3228 - val_accuracy: 0.9623 - val_loss: 0.1315
Epoch 2/20
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 25s 15ms/step - accuracy: 0.9692 - loss: 0.1022 - val_accuracy: 0.9725 - val_loss: 0.0887
Epoch 3/20
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 24s 14ms/step - accuracy: 0.9747 - loss: 0.0806 - val_accuracy: 0.9765 - val_loss: 0.0743
Epoch 4/20
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 24s 14ms/step - accuracy: 0.9791 - loss: 0.0709 - val_accuracy: 0.9762 - val_loss: 0.0762
Epoch 5/20
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 24s 14ms/step - accuracy: 0.9816 - loss: 0.0593 - val_accuracy: 0.9808 - val_loss: 0.0613
Epoch 6/20
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 24s 14ms/step - accuracy: 0.9825 - loss: 0.0576 - val_accuracy: 0.9787 - val_loss: 0.0730
Epoch 7/20
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 24s 14ms/step - accuracy: 0.9812 - loss: 0.0599 - val_accuracy: 0.9835 - val_loss: 0.0571
Epoch 8/20
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 24s 14ms/step - accuracy: 0.9843 -

# final tetsing our model 

In [34]:
score = model.evaluate(x_test , y_test , verbose =1)

313/313 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.9770 - loss: 0.0681


In [35]:
score

[0.0570196658372879, 0.9815999865531921]